### ISSUE TITLE
Animated Armoury/NewArmoury.esp compatibility issues

### ISSUE THREAD

**Issue by genderneutralnoun** [minis-patchers/SynWeaponKeywords#1]
So, I've had this issue for a while of, ever since I switched over to Synthesis, animations from Animated Armoury wouldn't get applied to weapons patched by this patcher. Finally, I got fed up with it and did some digging in xEdit. Turns out, there's two main things blocking certain weapons from doing their correct animations.

First: There's a keyword on every weapon in NewArmoury.esp called NAR_Sig. I have no idea how I'd go about adding NAR_sig to every weapon via your patcher; I'm not a coder, I just have a relatively basic understanding of xEdit. According to NickaNak(the author of AA)'s guides to creating custom claws and whips: "Nar_Sig - This is used by other mods that are compatible with mine, when this is on a weapon and another mod is set up correctly it’ll see this sig and not reset animations when switching weapons. Also, the NPC quest uses this for some weapons to check if their weapon is eligible for custom anims". So yeah, it'd be helpful to have that.

Second: Not all of the keywords in the patcher, or even in NewArmoury.esp have animations assigned to them with DAR. The old patches for AA changed spear weapons to WeapTypePike, and changed shortspear weapons to WeapTypeRapier. That would cause an inconsistency with mods like SkyUI Weapon Pack, or even just other mods that depend on WeapType keywords, though I don't really know of any besides the ones you already have in the source mod settings. This is not something that this patcher can solve; it is something that must be done by the author of Animated Armoury, or manually changed by users. I myself am planning to do two things: add a WeapTypeShortspear keyword to NewArmoury.esp, and add the WeapTypeSpear ID and WeapTypeShortspear ID to the Animated Armoury _conditions.txt files for pikes and rapiers, respectively. I've already made a comment on the AA Nexus page about this, since not everyone will be able to figure out this issue and fix it themselves. Hopefully the author will consider adding my suggestions. (The reason I can't just set the patcher to use "WeapTypePike" for spears and "WeapTypeRapier" for shortspears is because I use [SkyUI Weapon Pack](https://www.nexusmods.com/skyrimspecialedition/mods/37231), and doing so would cause spears to have the pike icon and shortspears to have the rapier icon. Shortspears don't have their own icon either, though... Regardless, I'm sure there will be other mods in the future that use weapon type keywords, or ones I don't know about. You probably get what I mean.)

Additional thing: All of the claw weapons in Animated Armoury have two additional keywords (alongside WeapTypeClaw and NAR_sig): NA_CantParry and NA_InflictBleed. It'd be really nice to have them get automatically added to claw type weapons.

Ultimately, the only things I'm asking of this patcher are:

1. The ability to add NAR_sig to every weapon type for AA by default, with it configurable which weapon types also add NAR_sig, in case someone wants to, say, add rapier animations to WeapTypeShortspear weapons and pike animations to WeapTypeSpear weapons. *wink* 

2. The ability to add NA_CantParry and NA_InflictBleed to weapons flagged as claws.

That is all, thank you for your time.

**Comment by Minizbot2012** [comment]
The whole situation of skyrim's custom weapon keywords is a mess. Shortspears and pikes are totally different historical weapon types. As far as NAR_sig goes I thought it was used in legacy code, but it would be simple to add all of these keywords to the respective weapon types, as its all defined in JSON. Finding the time to do so however, is not as simple.

**Comment by genderneutralnoun** [comment]
The Animated Armoury dev didn't seem particularly inclined to make the changes I suggested, so we're stuck on that front. There are two things I discovered, however:
- NAR_sig is, apparently, legacy code as you stated, at least in the case of the Dynamic Animation Replacer version.
- For the DAR version, the animations do not correctly apply to weapons with different vanilla weapon types due to animation file naming. For example, a spear with the WeapTypeSpear keyword but also the animation type TwoHandAxe does not get the spear animation applied, because the files for the the greatsword animations have the prefix 2hm_ while the files for the battleaxe/warhammer animations have the prefix 2hw_. I could copy and rename the files myself of course, but that would be an even more massive pain to do every time AA updates than the manual fixes I already do.
Is there a way to make every weapon flagged as a spear change its weapon animation type to Greatsword via the JSON config file? Because otherwise I have no idea how to fix this myself, sorry.

**Comment by Minizbot2012** [comment]
Ahh, that's why the old zEdit patcher messed with the animation types, and that will take code to replicate. I might have time this weekend to mess with this stuff again, hopefully.

**Comment by Minizbot2012** [comment]
Finally got time to mess with this, can you create a list of AA types to Base animation types, could really help me out. I will of course do this myself as well to update the base DB, but I also have code to be able to split One and Two handed Weapon types so that animations can apply to each type.

**Comment by Minizbot2012** [comment]
Let me know if there are any further issues in the currently posted code. But otherwise this can be marked as 90 percent fixed. I have added the abilities to do the animation types as requested, and gone through and set sane defaults (I think) and matches new armory for the most part. I have also updated the Database.json to add NAR_Sig to all currently supported New Armory Weapon Types
