### ISSUE TITLE
Using exclude still doesn't provide the intended results

### ISSUE THREAD

**Issue by zhongjiedong** [minis-patchers/SynWeaponKeywords#10]
[SynWeaponKeywords.txt](https://github.com/minis-patchers/SynWeaponKeywords/files/8758068/SynWeaponKeywords.txt)
[database.txt](https://github.com/minis-patchers/SynWeaponKeywords/files/8758073/database.txt)

I'm not trying to be annoying but I only used the EditorID option because the basic exclude didn't work, as you can see I have WeaptypePike excluding ShortSpear but it still applies it to Shortspear.

You say exclude takes priority but that doesn't look like it's working here
![2022-05-23 22_12_58-Synthesis](https://user-images.githubusercontent.com/20669755/169906924-11d188e9-d7be-4b3f-bd3c-de7b80c0846a.png)
.

**Comment by Minizbot2012** [comment]
Can you send me a image of the keywords under the editor id ShRedguardShortspear, I suspect there is a small visual issue with the log (xEdit or zEdit) as it doesn't seem to be adding both keywords in the log, but is listing them both under matching...

**Comment by Minizbot2012** [comment]
The exclude system was implemented at a different location than the main checking, I did not know as much LINQ when I originally wrote this than I did now... I suspect it is a visual issue, but a visual issue is a defect and is none the less an issue, while I suspect it did not impact the operation and end result of the patcher, it is still a bug (which should be fixed now). as a side effect this does simplify an if statement within the code.

**Comment by zhongjiedong** [comment]
It works well now, before even in plugin it was applying wrong keywords but now it's all correct.

**Comment by Minizbot2012** [comment]
Every keyword added has a separate log line, the log you provided did not have the log lines for the other keyword, which is how I found this
