### ISSUE TITLE
Blocking Error because it isn't passing IRunnabilityState on the Main branch -- 4 errors.

### ISSUE THREAD

**Issue by CipherArrow** [minis-patchers/SynWeaponKeywords#12]
Mutagen: 0.36.3
Synthesis: 0.22.1
Using the MAIN build and not experimental?: Yes

![image](https://user-images.githubusercontent.com/13478221/175760974-f8d7b41d-bc58-4ad5-91db-edcad47244c2.png)

I was trying to run your Synthesis Patcher for applying Weapon Keywords but got this despite running the patch within its own Synthesis group. I'm needing this because of Animated Amoury - DAR version requiring the zEdit version -- the patch itself isn't working with zEdit due to me having too many masters (over 700 mods). As you can see, I really need this patch that you're making. :) 

I hope the below errors occurring will help iron out the patch so it will pass the "IRunnabilityState" which Synthesis checks before enabling for use:
```

Program.cs(45,23): error CS1061: 'IRunnabilityState' does not contain a definition for 'ExtraSettingsDataPath' and no accessible extension method 'ExtraSettingsDataPath' accepting a first argument of type 'IRunnabilityState' could be found (are you missing a using directive or an assembly reference?)
Program.cs(51,30): error CS1061: 'IRunnabilityState' does not contain a definition for 'ExtraSettingsDataPath' and no accessible extension method 'ExtraSettingsDataPath' accepting a first argument of type 'IRunnabilityState' could be found (are you missing a using directive or an assembly reference?)
Program.cs(45,23): error CS1061: 'IRunnabilityState' does not contain a definition for 'ExtraSettingsDataPath' and no accessible extension method 'ExtraSettingsDataPath' accepting a first argument of type 'IRunnabilityState' could be found (are you missing a using directive or an assembly reference?)
Program.cs(51,30): error CS1061: 'IRunnabilityState' does not contain a definition for 'ExtraSettingsDataPath' and no accessible extension method 'ExtraSettingsDataPath' accepting a first argument of type 'IRunnabilityState' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by titanbass1** [comment]
I'm also seeing this.

**Comment by Minizbot2012** [comment]
The setting needs to be set to match for both synthesis and mutagen as I pulled in a pre-release feature into the main branch (I should've pulled it into an experimental branch until it released)

**Comment by CipherArrow** [comment]
Okay, thanks! 

BTW Minizbot2012 is talking about doing this:
![image](https://user-images.githubusercontent.com/13478221/175790386-ef0edde5-7abf-48f5-8a1c-51bbbed119f8.png)
