### ISSUE TITLE
Weapons using templates are being included

### ISSUE THREAD

**Issue by zhongjiedong** [minis-patchers/SynWeaponKeywords#16]
Weapons that have a template do not need to be patched as they derive their keywords from the base weapon. This is resulting in thousands of unnecessary overrides. 

I raised this recently with this patcher: https://github.com/Synthesis-Collective/speedandreachfixes/commit/5fb406c983d3b70b2723047d1c856e83a43315ae

Maybe this can be implemented here too?

**Comment by Minizbot2012** [comment]
a one line fix, but implemented.
