### ISSUE TITLE
certain LL weapon mods are unchanged when patched for animated armory

### ISSUE THREAD

**Issue by Hollowboye** [minis-patchers/SynWeaponKeywords#19]
I cannot for the life of me understand what's going on here.
Trying to add animations and such for weapons from Dark Souls Weapons from LL, as well as DS3 weapon pack from team tal. Neither of them work. 
Also tried manually adding the keywords via xedit, no luck there either.
Tried https://www.nexusmods.com/skyrimspecialedition/mods/45544 too.
Am I just stupid and don't understand what I'm doing or how AA works? Only nexus-downloaded patches makes this work, and when i try to make what i think is the exact same changes i see no effect.

Mod list: https://pastebin.com/KWWLQcw6
Lo: https://pastebin.com/QwESVxFg

![image_2022-11-27_225655486](https://user-images.githubusercontent.com/119281540/204204392-7ba1f6f8-da59-4bdc-9106-edfbf1d5969f.png)

picture shows a weapon that works, and one that does not.
have some videos too
https://cdn.discordapp.com/attachments/341362343273562122/1046629445181648896/2022-11-27_20-30-22.mp4
https://cdn.discordapp.com/attachments/341362343273562122/1046627438492385341/2022-11-27_20-22-52.mp4

**Comment by Minizbot2012** [comment]
Can I get the patcher's log output? It should be a text file from <Synthesis exe dir>/Logs/<Date>/<time> (the file should be named SynWeaponsKeywords.txt)

**Comment by Hollowboye** [comment]
> 

https://pastebin.com/h6cS9ZnY sure thing

**Comment by Minizbot2012** [comment]
Something I immediately see in the logs, is this:
`[175.8] Added Keyword : 000000:Null : WeapTypeSpear`
This should not be outputting this
Can you send me your DB from <Synthesis.exe Dir>/Data/SynWeaponKeywords/Database.json (its a plain text file)?
As a side note, I am now no longer injecting the keywords into this space if they're already there with what I just pushed...

**Comment by Minizbot2012** [comment]
Also just pushed a DB update, DB Injected Keywords I must've messed up when first creating that part... it was supposed to match Injected Animated Armory, but I was off by a value...

**Comment by Hollowboye** [comment]
> Also just pushed a DB update, DB Injected Keywords I must've messed up when first creating that part... it was supposed to match Injected Animated Armory, but I was off by a value...

So do I send you the dbI have without updating to that?

**Comment by Hollowboye** [comment]
Whoops, very new to actually using GitHub sry

**Comment by Hollowboye** [comment]
> Something I immediately see in the logs, is this: `[175.8] Added Keyword : 000000:Null : WeapTypeSpear` This should not be outputting this Can you send me your DB from <Synthesis.exe Dir>/Data/SynWeaponKeywords/Database.json (its a plain text file)? As a side note, I am now no longer injecting the keywords into this space if they're already there with what I just pushed...

https://pastebin.com/H3v2R34N

**Comment by Minizbot2012** [comment]
Yup, as I suspected, there is a bit of DB corruption on your end, thankfully it can be fixed by simply running the patcher right now and updating to DB V9 (its automatic). As far as the other issues, check back once you've run the patcher with DB V9.

**Comment by Hollowboye** [comment]
> 

Will do, is there any way to keep this sort of corruption from happening for future reference?

**Comment by Hollowboye** [comment]
Update, every other weapon works... *except for spears/pikes.*
Rapiers and halberds have expected behavior.

It also might be worth it to say that i think *any* mods that are supposed to spear anims dont work unless it has a patch from nexus or something similar, just not LL ones (although they of course wouldnt have much support)

DB: https://pastebin.com/xT6KCcyE
SWK.txt: https://pastebin.com/ch6DESju

**Comment by Hollowboye** [comment]
oh, and if there's anything else i can give you to help diagnose stuff please let me know

**Comment by Minizbot2012** [comment]
I think spears are the one I've almost given up on :( They always been my pet peeve, due to how mods define them differently, and then they don't always use similar settings animation / ESP / mesh wise.... Changing them in the ESP breaks animations badly, due to certain things being locked into the mesh, but I am looking into how I can handle those meshes, with XPMSSE and/or NiOverride, with a data distribution like how I handle SynFloraFix (my version of the flora fix). sadly I've not had much recent time to play skyrim as I am doing a Linux challenge, but, I've gotten MO2 to somewhat work at the moment (its a bit buggy and unstable, but it works).

**Comment by Hollowboye** [comment]
> 

No worries, don't mean to sound impatient or anything. Take your time, I appreciate the responses.

**Comment by Hollowboye** [comment]
oh hey i just noticed the new update cool

**Comment by Minizbot2012** [comment]
Its minor code-tweaks, that's about it, I am ready to move back to Windows soon hopefully.... hopefully...

**Comment by Hollowboye** [comment]
> Its minor code-tweaks, that's about it, I am ready to move back to Windows soon hopefully.... hopefully...

lol good luck

**Comment by Hollowboye** [comment]
Hi, the solution was staring me right in the face the entire time.
The weapon's animation type in DNAM *must* be TwoHandSword, or else the animations will not play.
I imagine other weapons in Animated Armory have similar reliance on this.

**Comment by Minizbot2012** [comment]
Yeah, the DNAM animation is tied to the mesh of the weapon, there's not really a great way to override them at the moment... this doesn't mean I am not trying a few things with the experimental option (still being prototyped, do not use and will likely require a script on the weapon in the end).

**Comment by Minizbot2012** [comment]
Closing due to stale / age
