### ISSUE TITLE
So what does this do exactly?

### ISSUE THREAD

**Issue by ghyujkilop** [minis-patchers/SynWeaponKeywords#2]

**Comment by zhongjiedong** [comment]
it adds keywords to weapons, very useful in the case of custom weapon mods to make them use animations from animated armoury for example

**Comment by Minizbot2012** [comment]
Another use of this is to enable certain custom icons added later on to skyui to Weapons, though that purpose is secondary. But please leave questions in the synthesis discord, and find me there, here they will be missed or left unanswered.
Also this is an issues section not a questions section, please use it as such.
