### ISSUE TITLE
SynWeaponKeywords Patch Can't Detect Glaives

### ISSUE THREAD

**Issue by AxielT** [minis-patchers/SynWeaponKeywords#20]
As I mentioned in the title, the patch cannot detect glaives. I tried it with the Green Dragon Crescent Blade included in Wolong Moveset. Also i tried Dwemer Tonal Weaponry - Glaives. How can I add keywords manually? Other weapons work fine (Katanas, curved swords, scythes, etc.)

**Comment by Minizbot2012** [comment]
Do those weapons contain "Glaive" in the weapon name?
Is there a common name on all of them, that you and I can use?
If you know the form id / esp I can add them to includes if all else fails.

**Comment by AxielT** [comment]
I added Green Dragon Crescent Blade to common names and it fixed problem for Green Dragon Crescent Blade included in Wolong Moveset. For the Dwemer Tonal Weaponry - Glaives i don't know how it fixed but It automaticly fixed for me. So i don't have any issue now. Thanks for help and you might be want to add Dragon Crescent Blade to common names.

**Comment by Minizbot2012** [comment]
Closing - stale / age
