### ISSUE TITLE
Support for static enchanted versions of weapons?

### ISSUE THREAD

**Issue by DoctahFrank** [minis-patchers/SynWeaponKeywords#21]
I'm running the [OMEGA/MLU-compatible version of Heavy Armory](https://www.nexusmods.com/skyrimspecialedition/mods/18479) that has a bunch of additional weapon records for the enchanted versions of the weapons. These aren't getting their keywords added, but all of the unenchanted versions are. Would it be possible to support these natively? It would be a lot of work to manually update my database to add all of the "quarterstaff of \<enchant\>" or "halberd of \<enchant\>", or individual FormIDs, since there are hundreds of records.

**Comment by Minizbot2012** [comment]
If these are using weapon templates (they should be) these weapon should be inheriting the keywords from the template (E.G the base weapon), not the record itself. See #16 for details on that

**Comment by DoctahFrank** [comment]
Ah, that makes sense. I'm not super familiar with how templated weapons work - didn't realize that only the base needs the keyword applied. Looks good, thanks for the response!
