### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by AxielT** [minis-patchers/SynWeaponKeywords#28]
I started getting this error after the update: 

> Downloading patch https://raw.githubusercontent.com/minis-patchers/SynDelta/main/SynWeaponKeywords/0.patch
> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'jd' with working directory 'C:\Users\Tamer\Desktop\adasd\Data\Skyrim Special Edition\SynWeaponKeywords'. The system cannot find the file specified.
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\Tamer\AppData\Local\Temp\Synthesis\ztmsnyju.aji\Git\i551ece5.fv3\Runner\SynPatcher\Program.cs:line 79
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
> --- End of stack trace from previous location ---
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187

**Comment by Minizbot2012** [comment]
Please hit the delete user data button in the bottom right under the settings tab (I changed how patches are applied).

**Comment by AxielT** [comment]
Unfortunately, I still get the same error.

**Comment by Minizbot2012** [comment]
Just try now (I changed how jd.exe is packed.

**Comment by AxielT** [comment]
Everything seems to be fine now. Thanks a lot!
