### ISSUE TITLE
All weapons are set hand to hand animation

### ISSUE THREAD

**Issue by SamuraiShogun1102** [minis-patchers/SynWeaponKeywords#3]
When running the patcher, all weapons are set to be unarmed animations

**Comment by Minizbot2012** [comment]
After the last update (which added the animation changes) you need to clear the Database, found in [synthesis exe path]\data\SynWeaponKeywords (delete the folder). Not going to automate this process as doing so would delete people's customization if any.

**Comment by SamuraiShogun1102** [comment]
Okay thanks
