### ISSUE TITLE
Blocking error

### ISSUE THREAD

**Issue by xaina222** [minis-patchers/SynWeaponKeywords#30]
Recently I was unable to run the patcher, it was fine a couple days ago ?
![2024-03-15 14_39_11-Synthesis](https://github.com/minis-patchers/SynWeaponKeywords/assets/163508542/d2385652-b9a3-4807-bff8-df7407e6ca22)

**Comment by Minizbot2012** [comment]
Only thing I can think of is that you're using an older version of this patcher.... line 42 has nothing to do with Newtonsoft.Json anymore... it literally is setting a string to String.Empty. I cannot / do not support old versions of the patch, I only support the current git latest.

**Comment by xaina222** [comment]
It worked after I deleted the patcher and install again so nvm
