### ISSUE TITLE
Settings do not get saved for keywords

### ISSUE THREAD

**Issue by AninoGamingTV** [minis-patchers/SynWeaponKeywords#31]
As per title, I edit the keywords under Katana2H from WeapTypeKatana to WeapTypeGreatKatana. I've added in the sources for the keyword itself. Whenever I successfully generate the patcher, the setting revert back to "default" settings.

I don't use WeapTypeKatana on Dai-Katana because I have separate movesets for them and it's a hassle to invert their priorities.

**Comment by Minizbot2012** [comment]
Known issue, I'm still working on things with the new database updater codebase

**Comment by Minizbot2012** [comment]
Working on a completely new structure, is being closed as legacy
