### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by ghyujkilop** [minis-patchers/SynWeaponKeywords#5]
Help me understand this, if I have a lot of mods, and I'm not sure which ones add knew types of weapons such as halberds, rapiers & quarterstaffs, would this patcher actually be useful for me? And is there a possible way to tell if we might get use from a patcher like this?

**Comment by Minizbot2012** [comment]
Do you have animated armory? This would make the vanilla katana's work with animated armory, along with their icons if you have dear diary and keywords within existing mods.
