### ISSUE TITLE
Can you please give an example of how this works/what it does?

### ISSUE THREAD

**Issue by ghyujkilop** [minis-patchers/SynWeaponKeywords#6]
Considering adding this patcher but I have no idea watch it does. Can you please tell me about the requirements, and what things will be changed in game by it? And is there any similar mods that do things like your patch are already on the Nexus?

**Comment by Minizbot2012** [comment]
This automatically adds keywords to weapons that match a specific type, so animated armor style items would not need a patch, say a mod adds a halberd and another has several halberds and animations for it implemented via keywords. This would add the needed keywords of a halberd animation given that the mod is supported.
