### ISSUE TITLE
Exclude names seem to be looking for exact string

### ISSUE THREAD

**Issue by zhongjiedong** [minis-patchers/SynWeaponKeywords#9]
[database.txt](https://github.com/minis-patchers/SynWeaponKeywords/files/8757554/database.txt)

Trying to run this will give the spear records pike as well.

**Comment by Minizbot2012** [comment]
exclude edit ID is to exclude a specific editor id as shown in xEdit, not phrases, next you have the spear commonName under pike. This is a fix your config situation.

**Comment by zhongjiedong** [comment]
Yes but the issue is that I have spears and shortspears, I need spears to receive the pike keyword since they are 2handed and similar to pikes

I have a similar issues with katanas and Dai-Katanas

**Comment by Minizbot2012** [comment]
I will only say this once more... Exclude edit ID is for editor ids, not phrases, use normal exclude for that

**Comment by Minizbot2012** [comment]
Also, excludes take priority over common names, excluding katana in dai-katana is counter productive, this is a situation of invalid data
